services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
        